Refs #23961: Add hri_installer script
Signed-off-by: Carlos Ferreira González <carlosferreira@eprosima.com>

diff --git a/vulcanexus_base/environment/vulcanexus_base-setup.bash.in b/vulcanexus_base/environment/vulcanexus_base-setup.bash.in
--- a/vulcanexus_base/environment/vulcanexus_base-setup.bash.in
+++ b/vulcanexus_base/environment/vulcanexus_base-setup.bash.in
@@ -32,3 +32,20 @@ disable_all_fastdds_statistics()
 {
     unset FASTDDS_STATISTICS
 }
+
+install_hri()
+{
+    local script_path="${VULCANEXUS_HOME%/}/share/hri/install_hri.sh"
+
+    if [ ! -f "${script_path}" ]; then
+        echo "ERROR: Could not install HRI because script was not found at '${script_path}'" >&2
+        return 1
+    fi
+
+    if [ ! -x "${script_path}" ]; then
+        echo "ERROR: Could not install HRI because script at '${script_path}' is not executable" >&2
+        return 1
+    fi
+
+    "${script_path}" "$@"
+}
